# Pandas and Numpy

In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/Crop_recommendation.csv')

print(df.shape)

df.head()

(2200, 8)


,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


### Filtering

In [24]:
high_rain_crops = df[df["rainfall"]> 200]

high_raincrops_list = high_rain_crops["label"].unique()

print(high_raincrops_list)

['rice' 'papaya' 'coconut']


In [38]:
extreme_weather = df[(df["temperature"]>30) & (df["humidity"]>90)]

print(extreme_weather['label'].unique())
print(len(extreme_weather))
extreme_weather.head()

['orange' 'papaya']
91


,N,P,K,temperature,humidity,ph,rainfall,label
1608,39,24,14,30.554726,90.903438,7.189260,106.071198,orange
1612,6,9,12,31.083689,90.143626,7.028746,109.689466,orange
1616,31,8,7,34.514651,93.638127,7.163246,103.568493,orange
1625,30,7,15,33.234533,91.060539,7.825532,115.765990,orange
1629,5,18,14,33.105698,93.484475,7.434119,119.170911,orange


### Statistics & Masking

In [43]:
df['is_hot'] = np.where(df['temperature'] > 25, 1, 0)

display(df.head())

matrix_np = df.iloc[:,0:3].values

print(matrix_np)

print(np.mean(matrix_np, axis = 0))

,N,P,K,temperature,humidity,ph,rainfall,label,is_hot
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,0
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,0
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,0
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,1
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,0


[[ 90  42  43]
 [ 85  58  41]
 [ 60  55  44]
 ...
 [118  33  30]
 [117  32  34]
 [104  18  30]]
[50.55181818 53.36272727 48.14909091]


### GroupBy

In [45]:
crop_summary = df.groupby('label').mean()

crop_summary = crop_summary.sort_values(by = 'rainfall', ascending = False)

display(crop_summary.head())

,N,P,K,temperature,humidity,ph,rainfall,is_hot
label,,,,,,,,
rice,79.89,47.58,39.87,23.689332,82.272822,6.425471,236.181114,0.30
coconut,21.98,16.93,30.59,27.409892,94.844272,5.976562,175.686646,1.00
jute,78.40,46.86,39.99,24.958376,79.639864,6.732778,174.792798,0.48
coffee,101.20,28.74,29.94,25.540477,58.869846,6.790308,158.066295,0.61
pigeonpeas,20.73,67.73,20.29,27.741762,48.061633,5.794175,149.457564,0.64


## Challenge

### TODO: Calculate the standard deviation of the 'temperature' column
### Hint: You can use pandas .std() or numpy .std()

In [50]:
std = df['temperature'].std()
print(std)

5.063748599958843


### TODO: Find the row with the maximum 'N' value, and retrieve its 'label'
### Hint: You can use .idxmax() or sort_values()

In [52]:
max_n = df['N'].idxmax()
crop_name = df.loc[max_n, 'label']
print(crop_name)

cotton


# Matplotlib & Seaborn

In [53]:
import seaborn as sns
import matplotlib.pyplot as plt

### Correlation Heatmap